spring:
  application:
    name: db-demo
  profiles:
    active: dev


---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: 10.0.0.110
      port: 27017
      username: mongo_4x5WDy
      password: mongo_3hdYBC
      authenticationDatabase: admin
      database: test
  datasource:
    dynamic:
      primary: db2
      strict: false
      datasource:
        db1:
          url: jdbc:mysql://10.0.0.110:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: mysql_TzYnEB
          driver-class-name: com.mysql.cj.jdbc.Driver
        db2:
          url: jdbc:mysql://10.0.0.110:3307/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: mysql_PymcGM
          driver-class-name: com.mysql.cj.jdbc.Driver
